"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class AuthorizationVerificationStatus(str, Enum):
    r"""Used to track the status of micro-authorizations. **Nullable** for Transactions Details."""
    NEW = 'new'
    VERIFIED = 'verified'
    FAILED = 'failed'
    EXPIRED = 'expired'
