"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CaptureStatus(str, Enum):
    r"""The status of the capture. **Nullable** for Transactions Details."""
    SUCCEEDED = 'succeeded'
    DECLINED = 'declined'
    ERROR = 'error'
