"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CardDisplayNetwork(str, Enum):
    r"""The card's network. **Nullable** for Transactions Details."""
    CREDIT_CARD = 'Credit Card'
    AMERICAN_EXPRESS = 'American Express'
    DINERS_CLUB = 'Diners Club'
    DISCOVER = 'Discover'
    JCB = 'JCB'
    MASTER_CARD = 'MasterCard'
    UNION_PAY = 'Union Pay'
    VISA = 'Visa'
