"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CardNetwork(str, Enum):
    r"""The card's network code. **Nullable** for Transactions Details. Note: LEGACY diners_club_us_ca now tagged as mastercard"""
    UNKNOWN = 'unknown'
    VISA = 'visa'
    MASTERCARD = 'mastercard'
    AMEX = 'amex'
    DISCOVER = 'discover'
    DINERS_CLUB_US_CA = 'diners_club_us_ca'
    JCB = 'jcb'
    UNIONPAY = 'unionpay'
    ALLIANCEDATA = 'alliancedata'
    CITIPLCC = 'citiplcc'
