"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CardStatus(str, Enum):
    r"""The card's status. **Nullable** for Transactions Details."""
    ACTIVE = 'active'
    CREATED = 'created'
    INACTIVE = 'inactive'
    TRANSIENT = 'transient'
