"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CardTokenType(str, Enum):
    r"""Used to define which payment processor generated the token for this credit card."""
    VANTIV = 'vantiv'
    APPLEPAY = 'applepay'
    BOLT = 'bolt'
    STRIPE = 'stripe'
    PLCC = 'plcc'
    APPLEPAY_ENCRYPTED_BLOB = 'applepay_encrypted_blob'
