"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from bolt_embedded_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional

class DiscountCategory(str, Enum):
    COUPON = 'coupon'
    GIFTCARD = 'giftcard'
    MANAGED_GIFTCARD = 'managed_giftcard'
    STORE_CREDIT = 'store_credit'
    AUTOMATIC_PROMOTION = 'automatic_promotion'
    MEMBERSHIP_DISCOUNT = 'membership_discount'
    MEMBERSHIP_GIFTCARD = 'membership_giftcard'
    SUBSCRIPTION_DISCOUNT = 'subscription_discount'
    REWARDS_DISCOUNT = 'rewards_discount'
    UNKNOWN = 'unknown'

class Type(str, Enum):
    r"""The type of discount."""
    FIXED_AMOUNT = 'fixed_amount'
    PERCENTAGE = 'percentage'
    FREE_SHIPPING = 'free_shipping'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CartDiscount:
    amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amount'), 'exclude': lambda f: f is None }})
    code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('code'), 'exclude': lambda f: f is None }})
    description: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('description'), 'exclude': lambda f: f is None }})
    r"""Used to define the discount offering."""
    details_url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('details_url'), 'exclude': lambda f: f is None }})
    r"""Used to provide a link to additional details, such as a landing page, associated with the discount offering."""
    discount_category: Optional[DiscountCategory] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('discount_category'), 'exclude': lambda f: f is None }})
    reference: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('reference'), 'exclude': lambda f: f is None }})
    r"""Used to define the reference ID associated with the discount available."""
    type: Optional[Type] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type'), 'exclude': lambda f: f is None }})
    r"""The type of discount."""
    

