"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ConsumerMembershipStatus(str, Enum):
    r"""True if user has an AllPass membership associated to their Bolt Account. **Nullable** for Transactions Details."""
    ACTIVE = 'active'
    CANCELLED = 'cancelled'
    DISABLED = 'disabled'
    FREE_TRIAL = 'free_trial'
