"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .address_account import AddressAccount
from .payment_method_account import PaymentMethodAccount
from .profile import Profile
from bolt_embedded_api import utils
from dataclasses_json import Undefined, dataclass_json
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateAccountInput:
    r"""The details needed to create a Bolt account."""
    profile: Profile = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('profile') }})
    r"""The first name, last name, email address, and phone number of a shopper."""
    addresses: Optional[List[AddressAccount]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('addresses'), 'exclude': lambda f: f is None }})
    r"""A list of physical shipping addresses associated with this account."""
    payment_methods: Optional[List[PaymentMethodAccount]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payment_methods'), 'exclude': lambda f: f is None }})
    r"""A list of payment methods associated with this account."""
    

