"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from bolt_embedded_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional

class CreditCardCreditViewStatus(str, Enum):
    r"""The status of the refund to a card."""
    SUCCEEDED = 'succeeded'
    DECLINED = 'declined'
    ERROR = 'error'
    PENDING = 'pending'
    IN_PROGRESS = 'in progress'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreditCardCreditView:
    merchant_event_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchant_event_id'), 'exclude': lambda f: f is None }})
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""
    status: Optional[CreditCardCreditViewStatus] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status'), 'exclude': lambda f: f is None }})
    r"""The status of the refund to a card."""
    

