"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class EmailStatus(str, Enum):
    r"""This is the status of the contact method."""
    ACTIVE = 'active'
    PENDING = 'pending'
    INACTIVE = 'inactive'
