"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import amount_view as shared_amount_view
from ..shared import i_free_shipping_discount_view as shared_i_free_shipping_discount_view
from bolt_embedded_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional

class ICartDiscountViewDiscountCategory(str, Enum):
    COUPON = 'coupon'
    GIFTCARD = 'giftcard'
    MANAGED_GIFTCARD = 'managed_giftcard'
    STORE_CREDIT = 'store_credit'
    AUTOMATIC_PROMOTION = 'automatic_promotion'
    MEMBERSHIP_DISCOUNT = 'membership_discount'
    MEMBERSHIP_GIFTCARD = 'membership_giftcard'
    SUBSCRIPTION_DISCOUNT = 'subscription_discount'
    REWARDS_DISCOUNT = 'rewards_discount'
    UNKNOWN = 'unknown'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ICartDiscountView:
    amount: Optional[shared_amount_view.AmountView] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amount'), 'exclude': lambda f: f is None }})
    code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('code'), 'exclude': lambda f: f is None }})
    r"""Discount code used."""
    description: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('description'), 'exclude': lambda f: f is None }})
    r"""Used to define the discount offering."""
    details_url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('details_url'), 'exclude': lambda f: f is None }})
    r"""Used to provide a link to additional details, such as a landing page, associated with the discount offering."""
    discount_category: Optional[ICartDiscountViewDiscountCategory] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('discount_category'), 'exclude': lambda f: f is None }})
    free_shipping: Optional[shared_i_free_shipping_discount_view.IFreeShippingDiscountView] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('free_shipping'), 'exclude': lambda f: f is None }})
    reference: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('reference'), 'exclude': lambda f: f is None }})
    r"""Used to define the reference ID associated with the discount available."""
    

