"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .address_view import AddressView
from .in_store_shipment import InStoreShipment
from bolt_embedded_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional

class InStoreShipment2DistanceUnit(str, Enum):
    MILE = 'mile'
    KM = 'km'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class InStoreShipment2:
    r"""A cart that is being prepared for shipment"""
    address: Optional[AddressView] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('address'), 'exclude': lambda f: f is None }})
    r"""The address object returned in the response."""
    distance: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('distance'), 'exclude': lambda f: f is None }})
    distance_unit: Optional[InStoreShipment2DistanceUnit] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('distance_unit'), 'exclude': lambda f: f is None }})
    shipment: Optional[InStoreShipment] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('shipment'), 'exclude': lambda f: f is None }})
    r"""A cart that is being prepared for shipment"""
    store_name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('store_name'), 'exclude': lambda f: f is None }})
    

