"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from bolt_embedded_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import List, Optional

class LoginViewActions(str, Enum):
    SET_PASSWORD = 'set_password'
    ROTATE_PASSWORD = 'rotate_password'

class LoginViewMethods(str, Enum):
    CODE = 'code'
    CODE_PASSWORD = 'code_password'
    PASSWORD = 'password'
    ROTATE_PASSWORD = 'rotate_password'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class LoginView:
    actions: Optional[List[LoginViewActions]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('actions'), 'exclude': lambda f: f is None }})
    methods: Optional[List[LoginViewMethods]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('methods'), 'exclude': lambda f: f is None }})
    sso_authorization_url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sso_authorization_url'), 'exclude': lambda f: f is None }})
    

