"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .merchant_onboarding_status_code import MerchantOnboardingStatusCode
from .merchant_status import MerchantStatus
from .transaction_operational_processor import TransactionOperationalProcessor
from .transaction_processor import TransactionProcessor
from bolt_embedded_api import utils
from dataclasses_json import Undefined, dataclass_json
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Merchant:
    created_at: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('created_at') }})
    r"""The date the merchant account was created.  **Nullable** for Transactions Details."""
    description: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('description') }})
    r"""The description of the merchant account. **Nullable** for Transactions Details."""
    operational_processors: List[TransactionOperationalProcessor] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('operational_processors') }})
    r"""**Nullable** for Transactions Details."""
    processor: TransactionProcessor = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('processor') }})
    r"""The processor used. **Nullable** for Transactions Details."""
    time_zone: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('time_zone') }})
    r"""The timezone of the merchant. **Nullable** for Transactions Details."""
    onboarding_status: Optional[MerchantOnboardingStatusCode] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('onboarding_status'), 'exclude': lambda f: f is None }})
    public_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('public_id'), 'exclude': lambda f: f is None }})
    r"""The unique public ID for the merchant's Bolt account. A merchant account contains many merchant divisions."""
    status: Optional[MerchantStatus] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status'), 'exclude': lambda f: f is None }})
    r"""The merchant's status:
      * `1` - Active
      * `2` - Inactive
      * `3` - Offboarding
    """
    

