"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class MerchantOnboardingStatusCode(str, Enum):
    NEW_MERCHANT = 'new_merchant'
    USER_CREATED = 'user_created'
    FORM_FILLED = 'form_filled'
    INTEGRATION_DONE = 'integration_done'
    LEGACY = 'legacy'
    PROCESSOR_SETTINGS_RECEIVED = 'processor_settings_received'
