"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class MerchantPlatform(str, Enum):
    r"""The type of platform being used for this merchant division."""
    NONE = 'none'
    BIG_COMMERCE = 'big_commerce'
    SHOPIFY = 'shopify'
    MAGENTO = 'magento'
    MAGENTO2 = 'magento2'
    WOO_COMMERCE = 'woo_commerce'
    DRUPAL = 'drupal'
    VOLUSION = 'volusion'
    PRESTASHOP = 'prestashop'
    NETSUITE = 'netsuite'
    MIVA = 'miva'
    COMMERCE_CLOUD = 'commerce_cloud'
