"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class MerchantStatus(int, Enum):
    r"""The merchant's status:
      * `1` - Active
      * `2` - Inactive
      * `3` - Offboarding
    """
    ONE = 1
    TWO = 2
    THREE = 3
