"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .address import Address
from .cart_create import CartCreate
from .processing_initiator import ProcessingInitiator
from .user_identifier import UserIdentifier
from .user_identity import UserIdentity
from bolt_embedded_api import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional

class MerchantCreditCardAuthorizationRechargeSource(str, Enum):
    DIRECT_PAYMENTS = 'direct_payments'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class MerchantCreditCardAuthorizationRecharge:
    r"""This request is used for authorizing an existing, saved card associated with the account."""
    UNSET='__SPEAKEASY_UNSET__'
    cart: CartCreate = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cart') }})
    credit_card_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('credit_card_id') }})
    r"""The unique ID associated to the saved credit card in the account's wallet."""
    division_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('division_id') }})
    r"""The unique ID associated to the merchant's Bolt Account division; Merchants can have different divisions to suit multiple use cases (storefronts, pay-by-link, phone order processing). Use the Bolt Merchant Dashboard to switch between divisions and find the division ID under `Merchant Division Public ID`."""
    source: MerchantCreditCardAuthorizationRechargeSource = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('source') }})
    user_identifier: UserIdentifier = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('user_identifier') }})
    r"""The object containing key lookup IDs associated with the shopper's account, such as the unique email address and phone number."""
    user_identity: UserIdentity = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('user_identity') }})
    auto_capture: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('auto_capture'), 'exclude': lambda f: f is None }})
    merchant_event_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('merchant_event_id'), 'exclude': lambda f: f is None }})
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""
    previous_transaction_id: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('previous_transaction_id'), 'exclude': lambda f: f is MerchantCreditCardAuthorizationRecharge.UNSET }})
    r"""The unique ID associated with to the shopper's previous subscription-based transaction. Leave `null` for standard, non-subscription transactions."""
    processing_initiator: Optional[ProcessingInitiator] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('processing_initiator'), 'exclude': lambda f: f is None }})
    r"""Defines which payment method was used to initiate the transaction."""
    shipping_address: Optional[Address] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('shipping_address'), 'exclude': lambda f: f is None }})
    r"""The Address object is used for billing, shipping, and physical store address use cases."""
    

