"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import cart_view as shared_cart_view
from ..shared import i_order_dynamic_content as shared_i_order_dynamic_content
from ..shared import order_external_data_view as shared_order_external_data_view
from bolt_embedded_api import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OrderView:
    cart: Optional[shared_cart_view.CartView] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cart'), 'exclude': lambda f: f is None }})
    r"""This is the cart object returned in a successful response."""
    dynamic_content: Optional[shared_i_order_dynamic_content.IOrderDynamicContent] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dynamic_content'), 'exclude': lambda f: f is None }})
    external_data: Optional[shared_order_external_data_view.OrderExternalDataView] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('external_data'), 'exclude': lambda f: f is None }})
    platform_user_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('platform_user_id'), 'exclude': lambda f: f is None }})
    requires_action: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('requires_action'), 'exclude': lambda f: f is None }})
    token: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('token'), 'exclude': lambda f: f is None }})
    user_note: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('user_note'), 'exclude': lambda f: f is None }})
    r"""Used by shoppers to make extra requests or provide details for gift messages."""
    

