"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Priority(str, Enum):
    r"""Describes the card's priority."""
    PRIMARY = 'primary'
    LISTED = 'listed'
