"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class RequestStatus(str, Enum):
    REVIEWED = 'reviewed'
    NEEDS_REVIEW = 'needs_review'
    UNKNOWN = 'unknown'
