"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class RiskReviewStatus(str, Enum):
    r"""Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team."""
    UNKNOWN = 'unknown'
    NEEDS_REVIEW = 'needs_review'
    REVIEWED = 'reviewed'
