"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TransactionStatus(str, Enum):
    r"""The transaction's status."""
    IN_PROGRESS = 'in_progress'
    COMPLETED = 'completed'
    CANCELLED = 'cancelled'
    FAILED = 'failed'
    PENDING = 'pending'
    CREATED = 'created'
    AUTHORIZED = 'authorized'
    REJECTED_REVERSIBLE = 'rejected_reversible'
    REJECTED_IRREVERSIBLE = 'rejected_irreversible'
