"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TransactionIndemnificationDecision(str, Enum):
    r"""Describes whether the transaction is indemnified by Bolt for fraud."""
    UNKNOWN = 'unknown'
    INDEMNIFIED = 'indemnified'
    NOT_INDEMNIFIED = 'not_indemnified'
