"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TransactionProcessorStatus(str, Enum):
    r"""The processor's status. Only `primary` and `active` processor are displayed."""
    PRIMARY = 'primary'
    ACTIVE = 'active'
    INACTIVE = 'inactive'
