"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class WebhooksType(str, Enum):
    r"""[Webhook events](https://help.bolt.com/developers/guides/webhooks/#transaction-hook-types) that trigger a notification to the URL.  **Note**:`newsletter_subscription` is only for merchant use cases."""
    PAYMENT = 'payment'
    CREDIT = 'credit'
    CAPTURE = 'capture'
    VOID = 'void'
    AUTH = 'auth'
    PENDING = 'pending'
    REJECTED_IRREVERSIBLE = 'rejected_irreversible'
    REJECTED_REVERSIBLE = 'rejected_reversible'
    FAILED_PAYMENT = 'failed_payment'
    NEWSLETTER_SUBSCRIPTION = 'newsletter_subscription'
    RISK_INSIGHTS = 'risk_insights'
    CREDIT_CARD_DELETED = 'credit_card_deleted'
